import "./globals.css";
import type { Metadata } from "next";
import { Inter, Public_Sans } from "next/font/google";
import Providers from "./_components/Providers";

// const inter = Inter({ subsets: ["latin"] });
const sans = Public_Sans({
	subsets: ["latin"],
	preload: true,
	variable: "--font-public-sans",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`bg-bp text-tp ${sans.className}`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
