export default function Page() {
	return (
		<div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
			<div>Page</div>
		</div>
	);
}
